name: bank_app
description: "Aplicación bancaria móvil - BankApp"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  # Internacionalización (HU 3.3)
  flutter_localizations:
    sdk: flutter
  # Navegación
  go_router: ^14.8.1
  # Estado
  flutter_riverpod: ^2.6.1
  # Freezed runtime
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  # Íconos y UI
  flutter_svg: ^2.0.17
  # Formateo de moneda/fechas
  intl: ^0.20.2
  # Almacenamiento local
  shared_preferences: ^2.5.3
  # HTTP
  dio: ^5.7.0
  # Animaciones
  animations: ^2.0.11
  # Google Fonts
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # Generación de código
  build_runner: ^2.4.14
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  # Genera AppLocalizations desde los archivos .arb (HU 3.3)
  generate: true

  assets:
    - assets/images/
    - assets/icons/
